version: '3.9'

services:
  codeception:
    image: codeception/codeception
    volumes:
      - .:/project
    depends_on:
      - webdriver
    networks:
      - testing-citilink

  webdriver:
    image: selenium/standalone-chrome
    shm_size: '3g'
    dns: 8.8.4.4
    ports:
      - '4444:4444'
      - '7900:7900'
    networks:
      - testing-citilink
    volumes:
      - /dev/shm:/dev/shm

networks:
  testing-citilink:
